### ISSUE TITLE
provide arche-md for subcollection

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/digitarium-static#5]
currently we plan with two subcollections, one for facs and one for xml/teis, for those we need some metadata, especially `acdh:hasDescription`

**Comment by claudiar16** [comment]
Anbei die Texte in englischer und deutscher Sprache:
[Zusätzliche Metadaten für Digitarium-Archivierung.docx](https://github.com/acdh-oeaw/digitarium-static/files/9682903/Zusatzliche.Metadaten.fur.Digitarium-Archivierung.docx)

**Comment by csae8092** [comment]
Subcollection Faksimiles

hasTitle [deutsch]: DIGITARIUM Faksimiles

hasTitle [englisch]: DIGITARIUM Facsimiles

hasDescription [deutsch]: Die Subcollection beinhaltet die Bilddigialisate der von der ÖNB eingescannten und vom Projektteam bei Bedarf ausgerichtete und/oder zugeschnittenen Zeitungsseiten.

hasDescription [englisch]: The subcollection contains the image files of the newspaper pages scanned by the ÖNB and aligned and/or cropped by the project team as required.

—---------------------------------------------------------------------------------------------------------------------

Subcollection TEIs

hasTitle [deutsch]: DIGITARIUM XML/TEI-Ausgaben

hasTitle [englisch]: DIGITARIUM XML/TEI issues

hasDescription [deutsch]: Die Subcollection beinhaltet die vom Projektteam im XML/TEI-Format annotierten Volltexte. 

hasDescription [englisch]: The subcollection contains the full texts, annotated by the project team in XML/TEI format. 

---------------------------------------------------------------------------------------------------------------------

Metadaten TopCollection

hasDescription [english]:

Wienerisches DIGITARIUM is a digital collection of more than 300 transcribed full text issues of the “Wien[n]erisches Diarium”, a historical newspaper that was founded in Vienna in 1703 and is still published under the title “Wiener Zeitung”. The issues provided as facsimiles and in XML/TEI P5 including different layers of annotation are evenly distributed over the 18th century and offer a reliable basis for a wide range of research interests.
The collection was created within the project “Das Wien[n]erische Diarium: Digitaler Datenschatz für die geisteswissenschaftlichen Disziplinen“ (PI: Claudia Resch) which was funded by the “go!digital2.0” program of the Austrian Academy of Sciences and carried out at the Austrian Centre for Digital Humanities and Cultural Heritage (ACDH-CH) from 1 March 2017 to 29 February 2020 (Project-Nr. GD 2016/16, ÖAW 0704).

hasDescription [deutsch]:
Das Wienerische DIGITARIUM ist eine digitale Sammlung von mehr als 300 transkribierten Volltextausgaben des "Wien[n]erischen Diariums", einer historischen Zeitung, die 1703 in Wien gegründet worden ist und heute noch unter dem Titel "Wiener Zeitung" erscheint. Die als Faksimiles und im XML/TEI-P5 Format bereitgestellten, mit verschiedenen Annotationsebenen versehenen Ausgaben sind gleichmäßig über das 18. Jahrhundert verteilt und bieten eine verlässliche Grundlage für ein breites Spektrum von Forschungsinteressen.
Die Sammlung entstand im Rahmen des Projekts "Das Wien[n]erische Diarium: Digitaler Datenschatz für die geisteswissenschaftlichen Disziplinen" (PI: Claudia Resch), das im Rahmen des "go!digital2.0"-Programms der Österreichischen Akademie der Wissenschaften gefördert und vom 1. März 2017 bis 29. Februar 2020 am Austrian Centre for Digital Humanities and Cultural Heritage (ACDH-CH) durchgeführt wurde (Projekt-Nr. GD 2016/16, ÖAW 0704).

hasAppliedMethodDescription [english]:

The methodical approach used for this collection follows a sequence of steps to be taken for every issue: Once digital pages provided by ANNO - Austrian Newspaper Online have been obtained, they were subjected to preprocessing and automatic deskewing. The recognition phase with layout analysis and text recognition relied on the Transkribus software. As results in recognizing broken scripts like German blackletter typeface are usually far from satisfactory, the project started out with a few issues that were transcribed completely by hand and used to train an initial model. Subsequently, the following issues to be processed were first recognized by the software and then corrected to an accuracy of around 99.7%. Each such corrected set then served as a training and test data set for a new model that was applied to the next batch of issues. The current model specifically trained for the Diarium generates text with an error rate of less than 1 per 100 characters within a standard paragraph from a good quality image.
In a next step the transcribed full-text was exported as a single TEI XML file per issue. Some post-processing was then required to prepare the text for publishing, e.g.the application of a basic whitespace tokenization in order to be able to address every “word” in the text with a unique identifier. Additionally, the pixel coordinates of the text regions were used to find their relative position within a page. This was done by applying a series of XSLT transformations to the files exported from Transkribus. As soon as all automated processes were completed, the results were checked visually and uploaded to the project’s web application DIGITARIUM.

hasAppliedMethodDescription [deutsch]:

Der methodische Ansatz zur Erstellung der Sammlung besteht aus folgenden Arbeitsschritten, die an jeder Ausgabe durchgeführt worden sind: Nach Empfang der von ANNO - Austrian Newspaper Online zur Verfügung gestellten digitalen Seiten wurden diese einer Vorverarbeitung und automatischen Entzerrung unterzogen. Die Erkennungsphase mittels Layoutanalyse und Texterkennung erfolgte über die Software Transkribus. Da die Ergebnisse bei der Erkennung von gebrochenen Schriften wie der Frakturschrift in der Regel wenig zufriedenstellend sind, startete das Projekt mit einigen wenigen Ausgaben, die vollständig von Hand transkribiert und zum Training eines ersten Modells verwendet wurden. Anschließend wurden die weiteren zu verarbeitenden Ausgaben zunächst von der Software erkannt und dann mit einer Genauigkeit von ca. 99,7 % korrigiert. Jedes auf diese Weise korrigierte Set von Ausgaben diente dann als Trainings- und Testdatensatz für ein neues Modell, das wiederum auf das nächste Set von Ausgaben angewandt wurde. Bei guter Bildqualität generiert das aktuelle, speziell für das Diarium trainierte Modell in Standardabsätzen einen Text mit einer Fehlerquote von weniger als 1 pro 100 Zeichen. In einem nächsten Schritt wurde der transkribierte Volltext pro Ausgabe als TEI-XML-Datei exportiert. Anschließend waren einige Nachbearbeitungen erforderlich, um den Text für die Veröffentlichung vorzubereiten, z. B. die Anwendung einer grundlegenden Whitespace-Tokenisierung, um jedes im Text vorkommende "Wort" eindeutig identifizierbar zu machen. Außerdem wurden die Pixelkoordinaten der Textregionen verwendet, um ihre relative Position innerhalb einer Seite zu bestimmen. Hierfür wurde eine Reihe von XSLT-Transformationen auf die aus Transkribus exportierten Dateien angewandt. Sobald alle automatisierten Prozesse abgeschlossen waren, wurden die Ergebnisse visuell überprüft und in das DIGITARIUM, die Webapplikation des Projekts, hochgeladen.

hasEditorialPractice [english]:

In order to create a scientifically sound basis for philological interpretation and allow as many research interests as possible, only complete issues have been included. Normalising interventions were preferably avoided and the historical language was reproduced as close to the printed original as possible. Hence, the typography of the original was largely retained, i.e. "u" and "v" or "i" and "j" have been preserved as well as ligatures, small caps or the change between Fraktur and Antiqua printing – only the differentiation of the two variants of "s" and "r" (so-called "long s" and "round r") was omitted. Consonantal ligatures, such as those found in "tz", "ct", "st" or "ff", are resolved in the transcribed text. Double hyphens (in compositions such as "Reichs=Raht") are represented by equal signs, since these come closest to the print image of the time. Unreadable passages as well as uncertain passages added by the editors have been marked in the transcription with angle brackets.

hasEditorialPractice [deutsch]:

Um eine wissenschaftlich fundierte Grundlage für die philologische Interpretation und möglichst viele Erkenntnisinteressen zu schaffen, wurden nur komplette Ausgaben in die Sammlung aufgenommen. Auf normalisierende und glättende Eingriffe wurde weitgehend verzichtet und der historischen Sprachstand der Druckvorlagen nahezu unverändert wiedergegeben. Die Typografie des Originals ist weitgehend beibehalten, d.h. „u“ und „v“ sowie „i“ und „j“ bleiben ebenso bestehen wie Ligaturen, Kapitälchen oder der Wechsel von Fraktur- und Antiquadruck – lediglich auf eine Differenzierung der beiden Varianten von „s“ und „r“ (sogenanntes „langes s“ und „rundes r“) wird verzichtet. Konsonantische Ligaturen, wie sie etwa bei „tz“, „ct“, „st“ oder „ff“ vorkommen, werden im transkribierten Text aufgelöst. Zusammenfügungen mit Mittelstrichschreibung (etwa in „Reichs=Raht“) werden mit dem Istgleichzeichen dargestellt, weil es dem damaligen Druckbild am nächsten kommt. Unleserliche Textstellen sowie durch die Herausgeber*innen ergänzte Textstellen werden in der Transkription mit spitzen Klammern gekennzeichnet.
